function [ manager ] = get_task_manager()

manager = TaskManager();

% Lay pulldown 60x10; Tricep 50x8
manager.add_new_task() ...
    .set_task_path('testdata/weightlifting_set1') ... 
    .set_task_format('bo') ... 
    .set_contributor('NESL') ...
    .add_a_set(16, 40, TYPE.lat_pulldown, 10) ...
    .add_a_set(94, 115, TYPE.tricep_curl, 8) ...
    .commit_task();

% Bicep 45x15; Tricep 45x10
manager.add_new_task() ...
    .set_task_path('testdata/weightlifting_set2') ... 
    .set_task_format('bo') ... 
    .set_contributor('NESL') ...
    .add_a_set(20, 50, TYPE.bicep_curl, 15) ...
    .add_a_set(114, 137, TYPE.tricep_curl, 10) ...
    .commit_task();

end

